---
version: '3'

services:

  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRESQL_PORT:-5432}:5432
    volumes:
      - ${DATA_VOLUMES_DIR:-.}/db/postgres:/var/lib/postgresql/data
