---
version: '3'

services:

  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile_elasticsearch
    environment:
      discovery.type: single-node
      cluster.name: elasticsearch
      network.bind_host: 0.0.0.0
      network.publish_host: 0.0.0.0
      xpack.security.enabled: 'false'
      bootstrap.memory_lock: 'true'
      ES_JAVA_OPTS: -Xms1g -Xmx1g
    # volumes:
    #  - ${DATA_VOLUMES_DIR:-.}/elastichsearch:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    ports:
      - ${ES_TRANSPORT_PORT:-9301}:9300
      - ${ES_REST_PORT:-9201}:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.0
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://elasticsearch:9200
    restart: always
    ports:
      - ${KIBANA_PORT:-5602}:5601
    links:
      - elasticsearch:elasticsearch
